
#	Ubuntu Xenial 64-bit Linux mit docker

BOX_IMAGE = "ubuntu/focal64"

Vagrant.configure("2") do |ubuntu|
  HOSTNAME = "ubuntu"
  ubuntu.vm.define HOSTNAME do |sububuntu|
    sububuntu.vm.box = BOX_IMAGE
    sububuntu.vm.network "private_network", ip: "192.168.100.4"
    #subconfig.vm.network "forwarded_port", guest:80, host:"8011", auto_correct: true
    sububuntu.vm.provider "virtualbox" do |vb|

      vb.memory = "2048"

    end
    sububuntu.vm.provision "shell", path: "script/docker.sh"
    sububuntu.vm.provision "shell", path: "script/setup.sh"

  end

  config.ssh.forward_agent = true
end