Vagrant.configure(2) do |config|
  HOSTNAME = "ubuntu"
  config.vm.define "ubuntu" do |ubuntu|
    ubuntu.vm.box = "ubuntu/xenial64"
    ubuntu.vm.network "private_network", ip: "192.168.100.4"
    #subconfig.vm.network "forwarded_port", guest:80, host:"8011", auto_correct: true
    ubuntu.vm.provider "virtualbox" do |vb|

      vb.memory = "2048"

    end
    ubuntu.vm.provision "shell", path: "script/docker.sh"


    end

    config.ssh.forward_agent = true
    end